### PR TITLE
Build STAC 0.9.0 Catalog for sen1floods11

### LINKED ISSUE #2: Sen1Floods11 STAC
[Sen1Floods11](https://github.com/cloudtostreet/Sen1Floods11) project provides a training, testing and validation dataset for training Sentinel1 flood inundation model. This issue is to prepare it to be used to train Raster Vision model as baseline for this project.

The images in the dataset are already well tiled, 512x512 GeoTiffs with 256x256 segment layout.

- [x] Copy dataset from google cloud to S3 bucket
- [x] Create STAC metadata for all chips
- [x] The file names are turse, ddd useful descriptions to STAC metadata from the [paper](http://openaccess.thecvf.com/content_CVPRW_2020/html/w11/Bonafilia_Sen1Floods11_A_Georeferenced_Dataset_to_Train_and_Test_Deep_Learning_CVPRW_2020_paper.html)
- [ ] Preserve the split of testing, training, validation sets already present.

The STAC catalog should use [label extension](https://github.com/radiantearth/stac-spec/tree/master/extensions/label) to link water masks with S1 imagery. 

The expected end result are four root catalogs: 
- Full Sen1Floods11 items
- Only Training  items
- Only Testing  items
- Only Validation items

The reason for this split is that it should eventually be possible to train Raster Vision model by pointing it to the training and testing catalogs only.

### PR DESCRIPTION
**Pull request by CloudNiner**
# Overview

This PR makes  a first attempt at a STAC 0.9.0 Catalog for sen1floods11 utilizing pystac 0.4.0.

Assets currently use Google Cloud Storage HTTPS links pending completion of #1 and a transfer of all the files to an AWS bucket owned by us. 

There's a big docstring in `main()` of `build.py` that describes each of the data folders in the sen1floods11 GCS bucket and the general structure of the generated STAC Catalog, along with a proposed alternative structure. 

## Demo

Here's the static catalog that this PR generates as a zip file:

[sen1floods11-catalog.zip](https://github.com/azavea/noaa-flood-mapping/files/4903685/sen1floods11-catalog.zip)

## Notes

I wanted to keep the `gs://` scheme links instead of using `https://` for assets but ran into issues with the default pip install of rasterio, which on my MacOS throws:
```
RasterioIOError: CPLRSASHA256Sign() not implemented: GDAL must be built against libcrypto++ or libcrypto (openssl)
```

To dodge this, since its temporary until we move the files, I just used vsicurl uris instead.

## Testing

Follow the instructions in `./catalogs/sen1floods11/README.md` to setup auth and generate a catalog.

Closes #2

### CODE REVIEW

**Comment by CloudNiner** [comment]
Noting that the original issue states:
> The expected end result are four root catalogs

This PR only generates the first of the four. There are two potential solutions to generate the other three train, test, validation catalogs and I be interested in getting input: 

1. Add a flag to the existing main that loads in the right CSV from the source data and filters the generated root catalog to only the items that are in the CSV. This gives a complete referenced catalog trimmed only to the items used in the paper's training, test and validation sets
2. Keep generating only a single catalog, but tag individual STAC Items in the catalog with a layer id (via the [STAC Layer Extension](https://github.com/azavea/stac4s/tree/master/docs/stac-spec/extensions/layer)) that indicates whether that item was in the original paper's training, test or validation set.

**Comment by echeipesh** [comment]
Checking this out and trying to run it:
`build.py` is trying to download `CNN_Chips_FTC.geojson` but its not there (anymore?)

Checking this out and I think the layout of `cnn_chips` bucket may have changed.

```
gs://cnn_chips/Sen1Floods11_labeled.tgz
gs://cnn_chips/cnn_chips.json
gs://cnn_chips/flood_bolivia_data.csv
gs://cnn_chips/flood_test_data.csv
gs://cnn_chips/flood_train_data.csv
gs://cnn_chips/flood_valid_data.csv
gs://cnn_chips/permanent_water_data.csv
gs://cnn_chips/permanent_water_test_data.csv
gs://cnn_chips/permanent_water_train_data.csv
gs://cnn_chips/permanent_water_validation_data.csv
gs://cnn_chips/NoQC/
gs://cnn_chips/Perm/
gs://cnn_chips/PermJRC/
gs://cnn_chips/QC_v2/
gs://cnn_chips/S1/
gs://cnn_chips/S1Flood/
gs://cnn_chips/S1Flood_NoQC/
gs://cnn_chips/S1Perm/
gs://cnn_chips/S1_NoQC/
gs://cnn_chips/S2/
gs://cnn_chips/S2Flood/
gs://cnn_chips/S2_NoQC/
gs://cnn_chips/cnn_checkpoints/
```

I think I may be misinterpreting the exception:

```
(noaa) ~/p/n/c/sen1floods11 ❯❯❯ python build.py                                                                                   feature/awf/sen1floods11-stac ✱
Created Catalog sen1floods11
Created STAC Collection: Sentinel1
Add STAC Catalog S1-Bolivia
Download:  CNN_Chips_FTC.geojson ./data/CNN_Chips_FTC.geojson
Traceback (most recent call last):
  File "/Users/eugene/.virtualenvs/noaa/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 951, in download_to_file
    transport, file_obj, download_url, headers, start, end, raw_download
  File "/Users/eugene/.virtualenvs/noaa/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 834, in _do_download
    download.consume(transport)
  File "/Users/eugene/.virtualenvs/noaa/lib/python3.7/site-packages/google/resumable_media/requests/download.py", line 153, in consume
    self._process_response(result)
  File "/Users/eugene/.virtualenvs/noaa/lib/python3.7/site-packages/google/resumable_media/_download.py", line 171, in _process_response
    response, _ACCEPTABLE_STATUS_CODES, self._get_status_code
  File "/Users/eugene/.virtualenvs/noaa/lib/python3.7/site-packages/google/resumable_media/_helpers.py", line 96, in require_status_code
    *status_codes
google.resumable_media.common.InvalidResponse: ('Request failed with status code', 404, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.PARTIAL_CONTENT: 206>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 413, in <module>
    main()
  File "/Users/eugene/.virtualenvs/noaa/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/eugene/.virtualenvs/noaa/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/eugene/.virtualenvs/noaa/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/eugene/.virtualenvs/noaa/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "build.py", line 309, in main
    collection_add_sentinel_chips(sentinel1, list(storage.ls("S1/"))[:2], "s1")
  File "build.py", line 89, in collection_add_sentinel_chips
    params["datetime"] = image_date_for_country(sentinel_version, country)
  File "build.py", line 31, in image_date_for_country
    os.path.basename(cnn_chips_geojson_file), cnn_chips_geojson_file
  File "/Users/eugene/proj/noaa-flood-mapping/catalogs/sen1floods11/storage/cloud_storage.py", line 48, in download
    blob.download_to_filename(target_filename)
  File "/Users/eugene/.virtualenvs/noaa/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 1024, in download_to_filename
    if_metageneration_not_match=if_metageneration_not_match,
  File "/Users/eugene/.virtualenvs/noaa/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 954, in download_to_file
    _raise_from_invalid_response(exc)
  File "/Users/eugene/.virtualenvs/noaa/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 3091, in _raise_from_invalid_response
    raise exceptions.from_http_status(response.status_code, message, response=response)
google.api_core.exceptions.NotFound: 404 GET https://storage.googleapis.com/download/storage/v1/b/cnn_chips/o/CNN_Chips_FTC.geojson?alt=media: ('Request failed with status code', 404, 'Expected one of', <HTTPStatus.OK: 200>, <HTTPStatus.PARTIAL_CONTENT: 206>)
```

**Review by echeipesh — COMMENTED** [review]
We're going a bit back and forth on this, getting cozy with STAC

Summary of latest discussion:

1. [x] Cut out the country, replace with country name property
This seemed like it would be helpful to nest it, but the process is weird and on further thought is unclear what the real benefit is.

2. [x] Use "source" asset on label item that points to source imagery for which the mask applies
This is addition that's required to comply with label item spec

3. [x] Hand Labelled items contain derived_from link to both S1 and S2 chips (2 links)
This is an instance where all the links are used

4. [x] Use labels consistent with Google Cloud repo for collection names and use description in the collections to make sense of what "QC", "noQC" actually means

5. [ ] Consider use multiprocessing to pull the bbox
May not be as big of a deal when pulling from S3 but to get the bbox for items from Google Cloud is painfully slow and it takes something like 20 minutes to build the full catalog.

**Comment by CloudNiner** [comment]
#### An update to the previous discussion

> Use "source" asset on label item that points to source imagery for which the mask applies
This is addition that's required to comply with label item spec

Looks like `source` ref actually belongs on `Link`: 
- https://github.com/radiantearth/stac-spec/tree/master/extensions/label#links-source-imagery
- https://github.com/radiantearth/stac-spec/blob/master/extensions/label/examples/spacenet-roads/roads_item.json#L155-L160

So that's what I'm going to go with, overriding the original task from the previous discussion.

#### New fun things

In a re-read of the label extension, it states:

> The raster label file (e.g. a GeoTIFF) should be included as an asset under the item. Along with the image file, a GeoJSON FeatureCollection asset should be included. That FeatureCollection should contain a single Feature, ideally a polygon geometry defining the extent of the raster.

...which seems redundant, since I've already created a LabelItem with a bbox and extent that describes the label raster. Am I off the mark here?

**Comment by echeipesh** [comment]
> ...which seems redundant, since I've already created a LabelItem with a bbox and extent that describes the label raster. Am I off the mark here?

Its not redundant because the projection of the raster could be something fun and bbox is a box in LatLng. So imagine converting a Landsat scene into some kind of mask. Its footprint is going to on the weird Landsat tilted path but the bbox will be rectilinear to LatLong grid.

**Comment by CloudNiner** [comment]
@echeipesh all items except the multiprocessing have been addressed (I hope!). Multiprocessing doesn't look quite as straightforward as I'd hoped. I think at this point I'd prefer to just spend the x minutes generating the full catalog rather than an hour implementing multiprocessing. We only have to generate the collection once each time we change the code.

**Comment by CloudNiner** [comment]
@echeipesh @moradology I think this as far as I take the task. Changes since last review should be clear from the commit history. I added a pair of caches that significantly speed up generation without resorting to async processing. Also a few datetime related bugfixes. Still takes about an hour to run but I doubt its worth optimizing further unless we expect many more iterations on this. There's now a `--debug` flag to easily switch between generating a subset of the catalog for testing purposes.

Uploaded the static catalog to `s3://sen1floods11-data/stac-catalog.zip` so you don't have to generate it yourselves.

**Review by echeipesh — APPROVED** [review]

**Pull request merged**
