### PR TITLE
Coregister HAND tifs for usfimr + s1 intersection

### LINKED ISSUE #70: Co-register HAND with Sentinel-1 chips
Connects: https://github.com/azavea/noaa-flood-mapping/issues/58

Raster Vision is gaining ability to source features from multiple rasters, but these rasters have to share CRS and pixel grid layout. Sentinel-1 and HAND doe not share those things and therefore a extra processing step is required.

Result of this issue should be HAND chips that match Sentinel-1 chips in their extent, resolution, projection.
Note: Because HAND rasters a bounded by HUC regions its possible that multiple HAND rasters would need to be sourced to cover a single Sentinel-1 chip.

Sentinel-1 chips specifically refer to the rasters created by https://github.com/azavea/noaa-flood-mapping/issues/56

### PR DESCRIPTION
**Pull request by CloudNiner**
This PR adds some code that take the following actions:

1. Load s1 chip catalog generated in #71 
1. Load HAND catalog
1. Perform a spatial join in geopandas to find HAND HUCs that intersect with each S1 chip
1. Extract a tif from the larger intersecting HAND HUC tifs that is reprojected and matched to the resolution and extent of each S1 chip
1. Upload that coregistered HAND tif to the same s3 "directory" as the s1 chip we used to match
1. Regenerate the usfimr s1 catalog so that it now includes assets linking to the HAND.tifs for each s1 chip

Here's the catalog, also available at s3://glofimr-sar-4326/glofimr-sar-catalog.zip

[usfimr-s1.zip](https://github.com/azavea/noaa-flood-mapping/files/5190980/usfimr-s1.zip)

## Example

Here's a coregistered raster output by coregister.py overlaid on top of the original HAND HUC tif in QGIS:

### Masked Area to be cut from the HAND tif

Screen Shot 2020-09-08 at 5 02 13 PM

### Coregistered HAND tif overlaid on the original HAND tif

Screen Shot 2020-09-08 at 5 02 18 PM

### GIF toggling the overlaid coregistered tif on and off

If you want to take a closer look, the files used for this example were:
- s3://hand-data/080102/080102hand.tif
- s3://glofimr-sar-4326/1/654e5272-a61c-4d69-bc71-aef74ccaf85f/16SCF_0_4/HAND.tif
- s3://glofimr-sar-4326/1/654e5272-a61c-4d69-bc71-aef74ccaf85f/16SCF_0_4/MASK.tiff

In particular, its worth pulling down a MASK.tiff and a HAND.tif and inspecting each with `gdalinfo` to ensure that their projections and resolutions match.

Closes #70

### CODE REVIEW

**Review by echeipesh — COMMENTED** [review]
This code actually looks pretty awesome, but the coregister function is not correct. Tracking for visible feature to feature in your GIF shows that offset is about 20m. The values on the boundary can go from 1.3 to 15 in a random spot that I picked. That could easily translate to error in the model.

Producing the same transformation for the HAND window using GT RasterSource made a raster that matches the HAND reproject by QGIS exactly. I think that this is potentially significant enough thats its worth tracking down the issue here.

**Comment by echeipesh** [comment]
```scala
scala> val handUri = "/tmp/usfimr-st/080102hand.tif"
handUri: String = /tmp/usfmir-st/080102hand.tif

scala> val handChipUri = "/tmp/usfimr-st/HAND.tif"
handChipUri: String = /tmp/usfimr-st/HAND.tif

scala> import geotrellis.raster.geotiff._
import geotrellis.raster.geotiff._

scala> val window = GeoTiffRasterSource(handChipUri).extent
window: geotrellis.vector.Extent = Extent(-89.22746431449217, 36.12261206773458, -88.99982841835738, 36.307140496267245)

scala> import geotrellis.proj4._
import geotrellis.proj4._

scala> import geotrellis.raster.resample._
import geotrellis.raster.resample._

scala> val rs = GeoTiffRasterSource(handUri).reproject(LatLng, method=Bilinear)
rs: geotrellis.raster.RasterSource = GeoTiffReprojectRasterSource(/tmp/usfimr-st/080102hand.tif, LatLng, DefaultTarget, Bilinear)

scala> val chip = rs.read(window).get
chip: geotrellis.raster.Raster[geotrellis.raster.MultibandTile] = Raster(ArrayMultibandTile(2459,1994,1,float32ud-3.4028234663852886E38),Extent(-89.22749995668677, 36.12259257432817, -88.99981477138098, 36.3072222040556))

scala> GeoTiff(chip, rs.crs).write("/tmp/usfimr-st/gt-hand.tif")
```

**Comment by CloudNiner** [comment]
Updated with a commit that should fix the coregister function by correctly setting the transform and resolution on the WarpedVRT so we don't need a windowed read into the VRT. 

Here's an updated gif that's super zoomed in:

**Comment by CloudNiner** [comment]
@echeipesh this has been updated to merge all of the relevant HUC rasters for a given S1 chip and I'm running `coregister.py` locally and uploading the 100 or so HAND chips. So its ready for a more complete review.

Here's some output from the running `coregister.py` script if you want to check a few of the result tifs:
```
Generating coraster for flood_1_chip_16SCF_0_0 using HAND ['080102', '080101', '080202', '071401', '051402']
        Saved to s3://glofimr-sar-4326/1/654e5272-a61c-4d69-bc71-aef74ccaf85f/16SCF_0_0/HAND.tif
Generating coraster for flood_1_chip_16SCF_0_1 using HAND ['080102', '080101', '080202']
        Saved to s3://glofimr-sar-4326/1/654e5272-a61c-4d69-bc71-aef74ccaf85f/16SCF_0_1/HAND.tif
Generating coraster for flood_1_chip_16SCF_0_2 using HAND ['080102', '080101', '080202']
        Saved to s3://glofimr-sar-4326/1/654e5272-a61c-4d69-bc71-aef74ccaf85f/16SCF_0_2/HAND.tif
Generating coraster for flood_1_chip_16SCF_0_3 using HAND ['080102']
        Saved to s3://glofimr-sar-4326/1/654e5272-a61c-4d69-bc71-aef74ccaf85f/16SCF_0_3/HAND.tif
Generating coraster for flood_1_chip_16SCF_0_4 using HAND ['080102']
        Saved to s3://glofimr-sar-4326/1/654e5272-a61c-4d69-bc71-aef74ccaf85f/16SCF_0_4/HAND.tif
Generating coraster for flood_1_chip_16SCG_0_3 using HAND ['071401', '051402']
        Saved to s3://glofimr-sar-4326/1/654e5272-a61c-4d69-bc71-aef74ccaf85f/16SCG_0_3/HAND.tif
Generating coraster for flood_1_chip_16SCG_0_4 using HAND ['080101', '071401', '051402']
```

Here's one that intersects 5 HUC zones: `s3://glofimr-sar-4326/1/654e5272-a61c-4d69-bc71-aef74ccaf85f/16SCF_0_0/HAND.tif`
Screen Shot 2020-09-09 at 5 08 12 PM

**Review by echeipesh — APPROVED** [review]

**Pull request merged**
